v7.4.11

diff --git a/7.4-fpm/Dockerfile b/7.4-fpm/Dockerfile
--- a/7.4-fpm/Dockerfile
+++ b/7.4-fpm/Dockerfile
@@ -1,12 +1,12 @@
-FROM php:7.4-fpm-alpine
+FROM php:7.4.11-fpm-alpine
 
 LABEL Maintainer="Jose Quintana <git.io/joseluisq>" \
-  Description="PHP-FPM v7.4 with essential extensions on top of Alpine Linux."
+    Description="PHP-FPM v7.4 with essential extensions on top of Alpine Linux."
 
 # Install dependencies
 RUN set -eux \
-	&& apk add --no-cache \
-		libxslt \
+    && apk add --no-cache \
+        libxslt \
         ca-certificates \
         composer \
         freetds \
@@ -39,7 +39,7 @@ RUN set -eux \
 
 # Development dependencies
 RUN set -eux \
-	&& apk add --no-cache --virtual .build-deps \
+    && apk add --no-cache --virtual .build-deps \
         autoconf \
         cmake \
         freetds-dev \
@@ -73,12 +73,12 @@ RUN set -eux \
         zlib-dev \
 \
 # Workaround for rabbitmq linking issue
-	&& ln -s /usr/lib /usr/local/lib64 \
+    && ln -s /usr/lib /usr/local/lib64 \
 # Enable ffi if it exists
-	&& set -eux \
-		&& if [ -f /usr/local/etc/php/conf.d/docker-php-ext-ffi.ini ]; then \
-			echo "ffi.enable = 1" >> /usr/local/etc/php/conf.d/docker-php-ext-ffi.ini; \
-		fi \
+    && set -eux \
+        && if [ -f /usr/local/etc/php/conf.d/docker-php-ext-ffi.ini ]; then \
+            echo "ffi.enable = 1" >> /usr/local/etc/php/conf.d/docker-php-ext-ffi.ini; \
+        fi \
 \
 ################################
 # Install PHP extensions
@@ -86,138 +86,138 @@ RUN set -eux \
 \
 # Install gd
     && ln -s /usr/lib/x86_64-linux-gnu/libXpm.* /usr/lib/ \
-	&& docker-php-ext-configure gd \
+    && docker-php-ext-configure gd \
         --enable-gd \
         --with-webp \
         --with-jpeg \
         --with-xpm \
         --with-freetype \
         --enable-gd-jis-conv \
-	&& docker-php-ext-install gd \
-	&& true \
+    && docker-php-ext-install gd \
+    && true \
 \
 # Install amqp
-	&& echo "/usr" | pecl install amqp \
-	&& docker-php-ext-enable amqp \
-	&& true \
+    && echo "/usr" | pecl install amqp \
+    && docker-php-ext-enable amqp \
+    && true \
 \
 # Install gettext
-	&& docker-php-ext-install gettext \
-	&& true \
+    && docker-php-ext-install gettext \
+    && true \
 \
 # Install gmp
-	&& docker-php-ext-install gmp \
-	&& true \
+    && docker-php-ext-install gmp \
+    && true \
 \
 # Install bcmath
-	&& docker-php-ext-install bcmath \
-	&& true \
+    && docker-php-ext-install bcmath \
+    && true \
 \
 # Install exif
-	&& docker-php-ext-install exif \
-	&& true \
+    && docker-php-ext-install exif \
+    && true \
 \
 # Install imagick
-	&& pecl install imagick \
-	&& docker-php-ext-enable imagick \
-	&& true \
+    && pecl install imagick \
+    && docker-php-ext-enable imagick \
+    && true \
 \
 # Install intl
-	&& docker-php-ext-install intl \
-	&& true \
+    && docker-php-ext-install intl \
+    && true \
 \
 # Install mcrypt
-	&& pecl install mcrypt \
-	&& docker-php-ext-enable mcrypt \
-	&& true \
+    && pecl install mcrypt \
+    && docker-php-ext-enable mcrypt \
+    && true \
 \
 # Install xmlrpc
-	&& docker-php-ext-configure xmlrpc --with-iconv-dir=/usr \
-	&& docker-php-ext-install xmlrpc \
-	&& true \
+    && docker-php-ext-configure xmlrpc --with-iconv-dir=/usr \
+    && docker-php-ext-install xmlrpc \
+    && true \
 \
 # Install memcache
-	&& pecl install memcache \
-	&& docker-php-ext-enable memcache \
-	&& true \
+    && pecl install memcache \
+    && docker-php-ext-enable memcache \
+    && true \
 \
 # Install mysqli
-	&& docker-php-ext-install mysqli \
-	&& true \
+    && docker-php-ext-install mysqli \
+    && true \
 \
 # Install oauth
-	&& pecl install oauth \
-	&& docker-php-ext-enable oauth \
-	&& true \
+    && pecl install oauth \
+    && docker-php-ext-enable oauth \
+    && true \
 \
 # Install pdo_mysql
-	&& docker-php-ext-configure pdo_mysql --with-zlib-dir=/usr \
-	&& docker-php-ext-install pdo_mysql \
-	&& true \
+    && docker-php-ext-configure pdo_mysql --with-zlib-dir=/usr \
+    && docker-php-ext-install pdo_mysql \
+    && true \
 \
 # Install pdo_dblib
-	&& docker-php-ext-install pdo_dblib \
-	&& true \
+    && docker-php-ext-install pdo_dblib \
+    && true \
 \
 # Install pcntl
-	&& docker-php-ext-install pcntl \
-	&& true \
+    && docker-php-ext-install pcntl \
+    && true \
 \
 # Install pdo_pgsql
-	&& docker-php-ext-install pdo_pgsql \
-	&& true \
+    && docker-php-ext-install pdo_pgsql \
+    && true \
 \
 # Install pgsql
-	&& docker-php-ext-install pgsql \
-	&& true \
+    && docker-php-ext-install pgsql \
+    && true \
 \
 # Install psr
-	&& pecl install psr \
-	&& docker-php-ext-enable psr \
-	&& true \
+    && pecl install psr \
+    && docker-php-ext-enable psr \
+    && true \
 \
 # Install soap
-	&& docker-php-ext-install soap \
-	&& true \
+    && docker-php-ext-install soap \
+    && true \
 \
 # Install ssh2
-	&& pecl install ssh2-1.2 \
-	&& docker-php-ext-enable ssh2 \
-	&& true \
+    && pecl install ssh2-1.2 \
+    && docker-php-ext-enable ssh2 \
+    && true \
 \
 # Install tidy
-	&& docker-php-ext-install tidy \
-	&& true \
+    && docker-php-ext-install tidy \
+    && true \
 \
 # Install xsl
-	&& docker-php-ext-install xsl \
-	&& true \
+    && docker-php-ext-install xsl \
+    && true \
 \
 # Install yaml
-	&& pecl install yaml \
-	&& docker-php-ext-enable yaml \
-	&& true \
+    && pecl install yaml \
+    && docker-php-ext-enable yaml \
+    && true \
 \
 # Install vips
-	&& pecl install vips \
-	&& docker-php-ext-enable vips \
-	&& true \
+    && pecl install vips \
+    && docker-php-ext-enable vips \
+    && true \
 \
 # Install zip
-	&& docker-php-ext-configure zip --with-zip \
-	&& docker-php-ext-install zip \
-	&& true \
+    && docker-php-ext-configure zip --with-zip \
+    && docker-php-ext-install zip \
+    && true \
 \
 # Clean up build packages
     && apk del .build-deps
 
 RUN set -eux \
 # Fix php.ini settings for enabled extensions
-	&& chmod +x "$(php -r 'echo ini_get("extension_dir");')"/* \
+    && chmod +x "$(php -r 'echo ini_get("extension_dir");')"/* \
 # Shrink binaries
-	&& (find /usr/local/bin -type f -print0 | xargs -n1 -0 strip --strip-all -p 2>/dev/null || true) \
-	&& (find /usr/local/lib -type f -print0 | xargs -n1 -0 strip --strip-all -p 2>/dev/null || true) \
-	&& (find /usr/local/sbin -type f -print0 | xargs -n1 -0 strip --strip-all -p 2>/dev/null || true)
+    && (find /usr/local/bin -type f -print0 | xargs -n1 -0 strip --strip-all -p 2>/dev/null || true) \
+    && (find /usr/local/lib -type f -print0 | xargs -n1 -0 strip --strip-all -p 2>/dev/null || true) \
+    && (find /usr/local/sbin -type f -print0 | xargs -n1 -0 strip --strip-all -p 2>/dev/null || true)
 
 # Copy PHP-FPM configuration files
 COPY 7.4-fpm/php-fpm.tmpl.conf /var/data/php-fpm/php-fpm.tmpl.conf
@@ -226,26 +226,26 @@ COPY 7.4-fpm/php.tmpl.ini /var/data/php-fpm/default-php.tmpl.ini
 
 RUN set -eux \
 # PHP-FPM templates directory
-	&& mkdir -p /var/data/php-fpm \
+    && mkdir -p /var/data/php-fpm \
 # Remove few PHP-FPM default config files
-	&& rm -rf /usr/local/etc/php-fpm.d/zz-docker.conf \
-	&& rm -rf /usr/local/etc/php-fpm.d/docker.conf \
+    && rm -rf /usr/local/etc/php-fpm.d/zz-docker.conf \
+    && rm -rf /usr/local/etc/php-fpm.d/docker.conf \
 \
 # Perform PHP-FPM testing
-	&& echo "date.timezone=UTC" > /usr/local/etc/php/php.ini \
-	&& php -v | grep -oE 'PHP\s[.0-9]+' | grep -oE '[.0-9]+' | grep '^7.4' \
-	&& /usr/local/sbin/php-fpm --test \
-	\
-	&& PHP_ERROR="$( php -v 2>&1 1>/dev/null )" \
-	&& if [ -n "${PHP_ERROR}" ]; then echo "${PHP_ERROR}"; false; fi \
-	&& PHP_ERROR="$( php -i 2>&1 1>/dev/null )" \
-	&& if [ -n "${PHP_ERROR}" ]; then echo "${PHP_ERROR}"; false; fi \
-	\
-	&& PHP_FPM_ERROR="$( php-fpm -v 2>&1 1>/dev/null )" \
-	&& if [ -n "${PHP_FPM_ERROR}" ]; then echo "${PHP_FPM_ERROR}"; false; fi \
-	&& PHP_FPM_ERROR="$( php-fpm -i 2>&1 1>/dev/null )" \
-	&& if [ -n "${PHP_FPM_ERROR}" ]; then echo "${PHP_FPM_ERROR}"; false; fi \
-	&& rm -f /usr/local/etc/php/php.ini
+    && echo "date.timezone=UTC" > /usr/local/etc/php/php.ini \
+    && php -v | grep -oE 'PHP\s[.0-9]+' | grep -oE '[.0-9]+' | grep '^7.4' \
+    && /usr/local/sbin/php-fpm --test \
+    \
+    && PHP_ERROR="$( php -v 2>&1 1>/dev/null )" \
+    && if [ -n "${PHP_ERROR}" ]; then echo "${PHP_ERROR}"; false; fi \
+    && PHP_ERROR="$( php -i 2>&1 1>/dev/null )" \
+    && if [ -n "${PHP_ERROR}" ]; then echo "${PHP_ERROR}"; false; fi \
+    \
+    && PHP_FPM_ERROR="$( php-fpm -v 2>&1 1>/dev/null )" \
+    && if [ -n "${PHP_FPM_ERROR}" ]; then echo "${PHP_FPM_ERROR}"; false; fi \
+    && PHP_FPM_ERROR="$( php-fpm -i 2>&1 1>/dev/null )" \
+    && if [ -n "${PHP_FPM_ERROR}" ]; then echo "${PHP_FPM_ERROR}"; false; fi \
+    && rm -f /usr/local/etc/php/php.ini
 
 # Copy util scripts
 COPY 7.4-fpm/envsubst.sh /envsubst.sh
